---

language: python
python: 2.7
sudo: required

services:
  - docker

# Install requirements
install:
  - pip install tox-travis

# Test all the scenarios against the Ansible
# versions defined in the tox.ini file
script:
  - tox

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

# TODO: this should run once
before_deploy:
  - pip install ansible==2.4
  - ansible-galaxy install --force --roles-path . -r \
    ./molecule/default/requirements.yml
